# Build Calendar every day

name: Build Calendar

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout main branch
      uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16'
    - name: build calendar
      run: npm ci && npm run generate
      env:
        NOTION_DATABASE: ${{ secrets.NOTION_DATABASE }}
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
    - name: deploy site
      run: npm ci && npm run deploy
      env:
        DEPLOY_TYPE: BACKEND
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CLOUDFLARE_WEBHOOK: ${{ secrets.CLOUDFLARE_WEBHOOK }}
